spring.config.import=configserver:
spring.application.name=candidat
spring.profiles.active=dev

spring.main.banner-mode=off
server.port=7880

spring.datasource.url=jdbc:postgresql://localhost:5432/jobboard_db?connectTimeout=60
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.hikari.pool-name=HikariCP
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true
spring.jpa.hibernate.ddl-auto=update



management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.health.db.enabled=false
management.health.diskspace.enabled=true

logging.level.root=debug
logging.charset.file=UTF-16
logging.file.name=${APPS_HOME}/logsMicroservices/candidat/candidatlog.log




